spring:
  kafka:
    consumer:
      bootstrap-servers: 172.16.212.76:9092
    producer:
      bootstrap-servers: 172.16.212.76:9092

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 1bab02deaaf8c73caa95dcdd8e84f6b7
            client-secret: xRqksavfetCVRiyF70dnTo3mmxO10dT5
            #redirect-uri: http://172.16.212.76:3000/login/kakao
            redirect-uri: http://localhost:3000/login/kakao
            #redirect-uri: http://172.16.212.76:8000/oauth/callback/kakao
            #redirect-uri: http://localhost:8080/oauth/callback/kakao
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
              - profile_image

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id