app:
  gateway:
    url: https://a6e386f26f9684920bae44157ccb228c-609974462.ap-northeast-2.elb.amazonaws.com
    #url: ${게이트웨이 주소}

spring:
  application:
    name: member

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://meeton-member.chke6w2cu29b.ap-northeast-2.rds.amazonaws.com:3306/member
    username: semicolon
    password: semicolon7!
#    url: ${db 주소}
#    username: ${db 사용자 이름}
#    password: ${db 비밀번호}

  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true
      secrets:
        enabled: true

  kafka:
    consumer:
      bootstrap-servers: ${카프카 서버 주소}:9092
    producer:
      bootstrap-servers: ${카프카 서버 주소}:9092

openapi:
  service:
    url: http://${서버 주소}:8000

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://${서버 주소}:8761/eureka
#
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    hostname: ${서버 주소}