spring:
  application:
    name: member

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #??? ??

  profiles:
    include: oauth

  config:
    import: application-private-kakao.yml

jwt:
  secret: /vUwAz/Vx78zX5/E4v6kjfbyoTRpYtOK2WT9rYcXeNPzDMuv1BlehYL113paVVYvUTyUIYg3kSZglWjEAJxgMw==

springdoc:
  api-docs:
    path: /member-api/v3/api-docs
  swagger-ui:
    path: /member-api/v3/swagger-ui.html

---
spring:
  profiles:
    active: dev, prod