app:
  gateway:
    url: https://a4a87b19384b54f64966378ae5e651f4-1374310802.ap-northeast-2.elb.amazonaws.com

spring:
  application:
    name: member

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://meeton-member.chke6w2cu29b.ap-northeast-2.rds.amazonaws.com:3306/member
    username: semicolon
    password: ${RDS_PASSWORD}

  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true
      secrets:
        enabled: true

  kafka:
    consumer:
      bootstrap-servers: 43.201.98.120:9092
    producer:
      bootstrap-servers: 43.201.98.120:9092

openapi:
  service:
    url: https://a4a87b19384b54f64966378ae5e651f4-1374310802.ap-northeast-2.elb.amazonaws.com:8000

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    enabled: false
